"""empty message

Revision ID: 7bac3be6436e
Revises: a3ceaddc34b0
Create Date: 2017-07-14 15:09:20.533275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bac3be6436e'
down_revision = 'a3ceaddc34b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('bucketlist', sa.Integer(), nullable=False))
    op.drop_constraint('item_bucket_list_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'bucket_list', ['bucketlist'], ['id'])
    op.drop_column('item', 'category')
    op.drop_column('item', 'location')
    op.drop_column('item', 'bucket_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('bucket_list', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('item', sa.Column('location', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('category', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_bucket_list_fkey', 'item', 'bucket_list', ['bucket_list'], ['id'])
    op.drop_column('item', 'bucketlist')
    # ### end Alembic commands ###
